---
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
  namespace: openstack-a
spec:
  networks:
  - dnsDomain: ctlplane.openstack-a.lab
    mtu: 1442
    name: ctlplane
    subnets:
    - allocationRanges:
      - end: 192.168.122.120
        start: 192.168.122.100
      - end: 192.168.122.200
        start: 192.168.122.150
      cidr: 192.168.122.0/24
      gateway: 192.168.122.1
      name: subnet1
      vlan: 10
  - dnsDomain: internalapi.openstack-a.lab
    mtu: 1442
    name: internalapi
    subnets:
    - allocationRanges:
      - end: 172.17.0.200
        start: 172.17.0.100
      cidr: 172.17.0.0/24
      name: subnet1
      vlan: 20
  - dnsDomain: storage.openstack-a.lab
    mtu: 1442
    name: storage
    subnets:
    - allocationRanges:
      - end: 172.18.0.200
        start: 172.18.0.100
      cidr: 172.18.0.0/24
      name: subnet1
      vlan: 21
  - dnsDomain: tenant.openstack-a.lab
    mtu: 1442
    name: tenant
    subnets:
    - allocationRanges:
      - end: 172.19.0.200
        start: 172.19.0.100
      cidr: 172.19.0.0/24
      name: subnet1
      vlan: 22
---
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
  namespace: openstack-b
spec:
  networks:
  - dnsDomain: ctlplane.openstack-b.lab
    mtu: 1442
    name: ctlplane
    subnets:
    - allocationRanges:
      - end: 192.168.123.120
        start: 192.168.123.100
      - end: 192.168.123.200
        start: 192.168.123.150
      cidr: 192.168.123.0/24
      gateway: 192.168.123.1
      name: subnet1
      vlan: 11
  - dnsDomain: internalapi.openstack-b.lab
    mtu: 1442
    name: internalapi
    subnets:
    - allocationRanges:
      - end: 172.17.1.200
        start: 172.17.1.100
      cidr: 172.17.1.0/24
      name: subnet1
      vlan: 30
  - dnsDomain: storage.openstack-b.lab
    mtu: 1442
    name: storage
    subnets:
    - allocationRanges:
      - end: 172.18.1.200
        start: 172.18.1.100
      cidr: 172.18.1.0/24
      name: subnet1
      vlan: 31
  - dnsDomain: tenant.openstack-b.lab
    mtu: 1442
    name: tenant
    subnets:
    - allocationRanges:
      - end: 172.19.1.200
        start: 172.19.1.100
      cidr: 172.19.1.0/24
      name: subnet1
      vlan: 32
