---
stages:
  - name: TopoLVM Dependencies
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/topolvm-deps-stages.yaml.j2")
      }}

  - name: Dependencies
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/deps-stages.yaml.j2")
      }}

  - name: Cinder LVM
    stages: >-
      {{
        lookup("ansible.builtin.file",
               "common/stages/cinder-lvm-label-stages.yaml")
      }}

  - name: VRF Label
    command: oc label node master-0 vrf=true

  - name: TopoLVM
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/topolvm-stages.yaml.j2")
      }}

  - name: OLM Openstack
    stages: >-
      {{
        lookup("ansible.builtin.template",
               "common/stages/olm-openstack-stages.yaml.j2")
      }}

  - name: NodeNetworkConfigurationPolicy (nncp)
    manifest: manifests/control-plane/networking/nncp.yaml
    wait_conditions:
      - >-
        oc wait -n openstack nncp -l osp/nncm-config-type=standard
        --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured
        --timeout=5m

  - name: NetworkAttchmentDefinition (NAD)
    manifest: manifests/control-plane/networking/nad.yaml

  # - name: EgressService
  #   manifest: manifests/control-plane/networking/egress-service-vrf.yaml

  - name: MetalLB - L2Advertisement and IPAddressPool
    manifest: manifests/control-plane/networking/metallb.yaml

  - name: Netcofnig
    manifest: manifests/control-plane/networking/netconfig.yaml

  - name: OpenstackControlPlane
    j2_manifest: manifests/control-plane/control-plane.yaml.j2
    wait_conditions:
      - >-
        oc wait -n openstack openstackcontrolplane controlplane
        --for condition=Ready --timeout=60m
