---
apiVersion: v1
data:
  LibvirtPassword: MTIzNDU2Nzg=
kind: Secret
metadata:
  name: libvirt-secret
  namespace: openstack-a
type: Opaque
---
apiVersion: v1
data:
  LibvirtPassword: MTIzNDU2Nzg=
kind: Secret
metadata:
  name: libvirt-secret
  namespace: openstack-b
type: Opaque
